module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("song_artists", [
      {
        song_id: 28,
        artist_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 29,
        artist_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 30,
        artist_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 31,
        artist_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 32,
        artist_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 33,
        artist_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 34,
        artist_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 35,
        artist_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 36,
        artist_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 37,
        artist_id: 8,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 38,
        artist_id: 9,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 39,
        artist_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 40,
        artist_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 41,
        artist_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 42,
        artist_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 43,
        artist_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 44,
        artist_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 45,
        artist_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 46,
        artist_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 47,
        artist_id: 10,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 48,
        artist_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 49,
        artist_id: 11,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 50,
        artist_id: 12,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 51,
        artist_id: 13,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 52,
        artist_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 53,
        artist_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 54,
        artist_id: 14,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 55,
        artist_id: 11,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 56,
        artist_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 57,
        artist_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 58,
        artist_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 59,
        artist_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 60,
        artist_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 61,
        artist_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 62,
        artist_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 63,
        artist_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        song_id: 64,
        artist_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("song_artists", null, {});
  },
};
